name: buildmate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # مكتبة اختيار الصور من الاستوديو
  image_picker: ^1.0.7

  # المكتبات الأساسية
  provider: ^6.1.1
  cupertino_icons: ^1.0.8

  # مكتبة فتح الروابط الخارجية (تمت إضافتها)
  url_launcher: ^6.2.5

  # المكتبات الأساسية الأخرى
  font_awesome_flutter: ^10.12.0

  # مكتبات Firebase المحدثة
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/